### ISSUE TITLE
Adding new device - Device does not exist/ code incorrect

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/dashboard-issues#17]
**Describe the bug**
When adding a device the error "the device does not exist or code is incorrect" comes up. 
When scanning for the QR code it says the QR code is invalid.

**To Reproduce**
1. Go to claim device
2. Enter the details manually or use the QR code scan
3. Click on add

**Expected behavior**
The device should be added to the dashboard

**Screenshots**
Sending them privately in Slack

**Smartphone (please complete the following information):**
 - Device: Google Pixel 1
 - OS: Android 9
 - Browser Chrome
 - Version Newest

**Comment by vpetersson** [comment]
@KevinWassermann94 This is most likely due to the device came with the first gen QR code. We pushed a fix for this today. Could you ask them to try again?

**Comment by hellfire-b** [comment]
@KevinWassermann94 Hello, I'm still getting this error on dashboard.nebra.com
