### ISSUE TITLE
Graph not showing data reward for the last 2 weeks

### ISSUE THREAD

**Issue by fouad-semaan** [NebraLtd/dashboard-issues#47]
![image](https://user-images.githubusercontent.com/38422316/147816363-535e85aa-e0aa-4d22-978e-1239c1d7c109.png)
![image](https://user-images.githubusercontent.com/38422316/147816387-301c43e8-a320-4428-b98c-d358531e1fb7.png)

**Comment by ko2sec** [comment]
same here.

**Comment by shawaj** [comment]
Think this should be resolved now @fouad-semaan @ko2sec ?

**Comment by ko2sec** [comment]
Hi @shawaj now it works like a charm! A little reminder, you need to empty your local storage on browser just to gather new graph data, otherwise it will still show old buggy graph.
